### ISSUE TITLE
Add V8 inspector to dev mode

### ISSUE THREAD

**Issue by justinsisley** [justinsisley/Invisible-Framework#23]
V8 Inspector

Run node with --inspect, it will tell you a URL. Paste that URL into Chrome. Boom, debugging Node in the Chrome DevTools. Happy days. There’s a how-to by Paul Irish over here.

Should log out the inspector URL when logging the server URLs.

**Comment by justinsisley** [comment]
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.helopxmiu

**Comment by preethamlv** [comment]
👍
